DATA = "P"
TRAIN = True
TEST_ON_BOTH_DATA = False
POOL = 4
LEARNING_RATE = 1e-2
TOTAL_EPOCHS = 500

EARLY_STOPPING = True
EARLY_STOPPING_COUNT = 50

CREATE_TEST_MASK = True

RESULT_PATH = "./result"
DATA_PATH = "data"

NOTIFY = True

# Transformations
TRANSFORM = False

HORIZONTAL_FLIP = False
VERTICAL_FLIP = False
SHEAR = False
GAUSSIAN_BLUR = False
